# Generated by Django 3.1 on 2020-10-18 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_auto_20201017_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
