# Generated by Django 3.1 on 2020-10-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_history',
            name='image',
        ),
    ]
