# Generated by Django 3.1 on 2020-10-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_remove_restaurant_history_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='chef',
            options={'verbose_name': 'Chef', 'verbose_name_plural': 'Chefs'},
        ),
        migrations.AlterModelOptions(
            name='restaurant_history',
            options={'verbose_name': 'Restaurant History', 'verbose_name_plural': 'Restaurant History'},
        ),
        migrations.AlterModelOptions(
            name='why_choose_us',
            options={'verbose_name': 'Why Choose Us', 'verbose_name_plural': 'Why Choose Us'},
        ),
    ]
